extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  indentation:
    spaces: consistent
    indent-sequences: consistent
    check-multi-line-strings: false
  document-start: disable
  empty-values:
    level: warning
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  truthy: disable
  line-length:
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
