#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &> /dev/null) && shopt -s inherit_errexit

# one.bash:usage
if (($# == 0)) || [[ $1 == -h ]] || [[ $1 == --help ]]; then
	cat << EOF
Usage: $ONE_SUB $(basename "$0") <file>
Desc: Create a backup for the file
EOF
	exit 0
fi

# one.bash:completion
if [[ "${1:-}" == --complete ]]; then
	if ((COMP_CWORD < 3)); then
		result=$(compgen -f -- "$2")
		if [[ -d $result ]]; then
			compgen -f -- "$result/"
		else
			echo "${result[@]}"
		fi
	fi
	exit 0
fi

file=$1
ext=bak
backup_file=${file}.${ext}

if [[ -e ${backup_file} ]]; then
	echo "Cannot create ${backup_file}. File existed." >&2
	exit 1
fi

if [[ -d $file ]]; then
	mv "$file" "$backup_file"
else
	cp "$file" "$backup_file"
fi

echo "Created backup file: $backup_file"
