#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

declare -A map=(
  [close-all]=close_all_windows
  [help]=help
)

# one.bash:completion
if [[ "${1:-}" == "--complete" ]]; then
  printf '%s\n' "${!map[@]}"
  exit 0
fi

# one.bash:usage
if (( $# == 0 )) || [[ $1 == -h ]] || [[ $1 == --help ]]; then
  cat <<EOF
Usage: $ONE_SUB $(basename "$0") [OPTIONS] <ARGUMENTS>

Arguments:
  close-all      Close all windows

Options:
  -h|--help      Show help
EOF

  exit 0
fi

close_all_windows() {
  chrome-cli list windows | \
    awk '{print $1}' | \
    sed -E 's/\[(.*)\]/\1/g' | \
    xargs -n1 chrome-cli close -w

  echo "[Done]"
}

readonly name=$1
shift

${map[$name]} "$@"
