#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:usage
if [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
	cat <<EOF
Usage: $ONE_SUB $(basename "$0")
Desc: List docker images in sort
EOF
	exit 0
fi

docker images | tail -n +2 | sort -h -k 7
