#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:usage
if (($# == 0)) || [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
	cat <<EOF
Usage: $ONE_SUB $(basename "$0") <URL>
Desc: Run htrace in docker. https://github.com/trimstray/htrace.sh
EOF
	exit 0
fi

readonly URL=$1

docker run --rm -it --name htrace djerfy/htrace -u "$URL" -s -h
