#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:usage
if [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
  cat <<EOF
Usage: $ONE_SUB $(basename "$0")
Desc: List environment variable MANPATH
EOF
  exit 0
fi

cmd() {
  echo "$MANPATH" | tr ":" "\n" | nl -w 3
}

if which fzf &>/dev/null; then
  cmd | fzf | awk '{printf "%s\n", $2}'
else
  cmd
fi
