#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:usage
if [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
  cat <<EOF
Usage: $ONE_SUB $(basename "$0")
Desc: List environment variable PATH
EOF
  exit 0
fi

echo "$PATH" | tr ":" "\n" | nl
