#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:usage
if [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
	# editorconfig-checker-disable
	cat <<EOF
Usage: $ONE_SUB $(basename "$0") [OPTIONS]
Desc: List environment variable PATH
Options:
  -a          Show all paths
EOF
	# editorconfig-checker-enable
	exit 0
fi

cmd() {
	echo "$PATH" | tr ":" "\n" | nl -w 3
}

if [[ ${1:-} == -a ]]; then
	cmd
elif which fzf &>/dev/null; then
	cmd | fzf | awk '{printf "%s\n", $2}'
else
	cmd
fi
