#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &> /dev/null) && shopt -s inherit_errexit

# one.bash:usage
if (($# == 0)) || [[ $1 == -h ]] || [[ $1 == --help ]]; then
	cat << EOF
Usage: $ONE_SUB $(basename "$0") [<LENGTH>] [<CHARACTERS>]
Desc: Output random string
Args:
  <LENGTH>      the length of output [Defaults: 10]
  <CHARACTERS>  the allowed characters of output [Defaults: a-zA-Z0-9@#*=[]]
EOF
	exit 0
fi

# shellcheck disable=1090
source "$ONE_LOBASH_FILE"

l.random "${1:-}" "${2:-}"
