#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:usage
if (( $# == 0 )) || [[ $1 == -h ]] || [[ $1 == --help ]]; then
  cat <<EOF
Usage: $ONE_SUB $(basename "$0") [<LENGTH>] [<CHARACTERS>]
Desc: Output random string
Args:
  <LENGTH>      the length of output [Defaults: 10]
  <CHARACTERS>  the allowed characters of output [Defaults: a-zA-Z0-9@#*=[]]
EOF
  exit 0
fi

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

# shellcheck source=../deps/lobash.bash
source "$SCRIPT_DIR/../deps/lobash.bash"

l.random "${1:-}" "${2:-}"
