#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:completion
if [[ "${1:-}" == --complete ]]; then
  if (( COMP_CWORD < 3 )); then
    result=$(compgen -f -- "$2")
    if [[ -d $result ]]; then
      compgen -f -- "$result/"
    else
      echo "${result[@]}"
    fi
  fi
  exit 0
fi

# one.bash:usage
if (( $# == 0 )) || [[ $1 == -h ]] || [[ $1 == --help ]]; then
  cat <<EOF
Usage: $ONE_SUB $(basename "$0") <PATH>
Desc: Create a bash script file on <PATH>. And chmod +x <PATH>.
Arguments:
  <PATH>   Absolute path for new script
EOF
  exit 0
fi

main() {
  local path=$1
  if [[ -e $path ]]; then
    "$EDITOR" "$path"
    exit $?
  fi

  echo "#!/usr/bin/env bash" > "$path"
  chmod +x "$path"
  "$EDITOR" "$path"
}

main "$@"
