#!/usr/bin/env bash

# one.bash:usage
if [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
  cat <<EOF
Usage: $ONE_SUB $(basename "$0")
Desc: Show UTC Time
EOF
  exit 0
fi

date -u "+%Y-%m-%dT%H:%M:%SZ"
