#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

# one.bash:usage
if [[ ${1:-} == -h ]] || [[ ${1:-} == --help ]]; then
  cat <<EOF
Usage: $ONE_SUB $(basename "$0") [<INTERFACE>]
Desc: Show WiFi password
Args:
  <INTERFACE>  Local network interface [Default: en0]
EOF
  exit 0
fi

if [[ $(uname -s) != Darwin ]]; then
  echo The command only support MacOS >&2
  exit 4
fi

get_wifi_name() {
  local prefix='Current Wi-Fi Network: '
  networksetup -getairportnetwork "$wifi_interface" | cut -c "$(( ${#prefix} + 1))"-
}

wifi_interface=en0
if (( $# > 0 )); then
  wifi_name=$1
else
  wifi_name=$(get_wifi_name)
fi

echo "WiFi Name: $wifi_name"

# It will pop up a password window to query your system password
output=$(security find-generic-password -wga "$wifi_name" 2>&1 || true)

if [[ $output == 'security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.' ]]; then
  echo "This WiFi interface not found or no need password"
else
  echo "Password: $output"
fi
